### ISSUE TITLE
Use of prettier/standalone and prettier/parser-babel packages causes webpack errors, runtime errors 

### ISSUE THREAD

**Issue by gkjohnson** [foxglove/rosmsg-serialization#35]
Hello! I just got around to upgrading my work to use the foxglove implementation of rosbag and associated packages and I noticed [these lines](https://github.com/foxglove/rosmsg-serialization/blob/851b76737780646528c177d73e57bcf3ef2a3fa6/src/buildReader.ts#L227-L233) causing some issues.

I'm using webpack and even though I'm not using `LazyMessageReader` webpack still logs errors that these packages can't be found. And if you _do_ use `LazyMessageReader` run time errors will be thrown. Are these lines intended to be removed before distribution?

Thanks!

**Comment by jtbandes** [comment]
Can you share the exact errors you're seeing? I've seen some related **warnings** (not errors) from webpack before, that ultimately are caused by an import of TypeScript, and we've worked around them in some cases: https://github.com/foxglove/studio/pull/1236

For the prettier ones specifically I filed an issue and it was fixed: https://github.com/prettier/prettier/issues/11076 but I'm not sure we've updated to this version yet, or it's possible it regressed again.

**Comment by gkjohnson** [comment]
These are the errors I'm seeing with webpack 5.9.0 with file paths redacted:

> ```
> ERROR in ./node_modules/@foxglove/rosmsg-serialization/dist/esm/buildReader.js 195:25-55
> Module not found: Error: Can't resolve 'prettier/standalone' in '<local path>/node_modules/@foxglove/rosmsg-serialization/dist/esm'
> ```

> ```
> ERROR in ../../../node_modules/@foxglove/rosmsg-serialization/dist/esm/buildReader.js 197:28-60
> Module not found: Error: Can't resolve 'prettier/parser-babel' in '<local path>/node_modules/@foxglove/rosmsg-serialization/dist/esm'
> ```

I expect you'd always see these when building with `rosmsg-serialization` unless you have prettier globally installed on your system. To be clear the page can still be run but if you try to instantiate a `LazyMessageReader` you'll see runtime errors because webpack could not find the packages during build.

> If you're using webpack, it should compile out that block when you use `--mode production`.

Yeah though I do wonder if this is still the case when using other build systems. I don't believe rollup implicitly defines "process.env" (so it might fail in that case, too) or strips code in constant conditions by default. I do see what you're trying to do with the "format" function I'm just not sure what the best way to generally  distribute a package like that is 🤔. At least the require statements could be wrapped in a try catch so the code will work at run time but I don't think that will get rid of the logged build-time errors.

**Comment by jtbandes** [comment]
Do you get any output about missing dependencies when you run yarn install?

**Comment by jtbandes** [comment]
Oh, I think the problem is just that these are devDependencies. I guess we can either add it as a dependency, somehow make it a weak dependency, or move the code that uses it into tests only (so the the snapshot tests can be nicely formatted).

**Comment by gkjohnson** [comment]
> move the code that uses it into tests only (so the snapshot tests can remain nicely formatted).

I think this is what I'd prefer since it's really for debugging the package itself. Something like a function body formatter callback that defaults to just returning the input might work if you're looking the tests to output nicely formatted lines if the function fails to run. I'm not sure what the right way is to make an optional dependency that wouldn't also make webpack complain.

**Comment by jtbandes** [comment]
> …it's really for debugging the package itself…

IMO it's nice for the output to always be nicely formatted — helps when stepping through in a browser's debugger and such — but I also know that prettier is a fairly hefty dependency to be pulling in at runtime 😢

**Comment by defunctzombie** [comment]
I think we need to remove this dependency from runtime and keep it for testing. I agree it is nice for some cases but there is a usage and install cost that is rather unpleasant for an otherwise small library.
