### ISSUE TITLE
MessageWritter gone wrong will using special character likes é,à,â,ô...

### ISSUE THREAD

**Issue by tfalkenberg2903** [foxglove/rosmsg-serialization#360]
**Description**
While i'll try to serialize my object using new MessageWritter().writeMessage(myRequest), myRequest containing an object with a key name:string of value 'béta' the serialization modify my string to 'bét', it remove one character per special character . 
example :
'béta' ==> 'bét'
'bééta' ==> 'bé'
'béééta' ==>'b'

- Version:2.0.2
- Platform: macOs

**Steps To Reproduce**

call the function MessageWriter().writeMessage({name:'béta'}) store it in a const
then use MessageReader().readMessage(myConst) you'll have a string containing 'bét'

here is a sample to reproduce the issue :

    const writer = new MessageWriter(parse("string name"));
    const reader = new MessageReader(parse("string name"));
    const test = writer.writeMessage({ name: "béta" });
    console.log("=== result === ", reader.readMessage(test));

this sample will print : Record {name: 'bét'} 

**Expected Behavior**

**Comment by jtbandes** [comment]
Could you please provide a complete sample program that reproduces the issue?

**Comment by jtbandes** [comment]
This should fix it, please have a look: https://github.com/foxglove/rosmsg-serialization/pull/361

**Comment by tfalkenberg2903** [comment]
Yes this fix it. Thanks a lot.

**Comment by jtbandes** [comment]
Fixed in v2.0.3. Thanks for the report!
